### ISSUE TITLE
cosmetically speaking.. some pages may need attention to the margins..

### ISSUE THREAD

**Issue by DJ-Sparky** [nehardev-organization/mitegra.mk#5]
For smaller screen sizes .. 1280 etc..

The homepage a little overlap on the right hand side.
The main "Plumber" etc pages maybe need a little 1.5 or 2rem etc on both sides.

The Contact page is a good example of where it all fits nice.. Id suggest follow that as an example.

**Comment by xDeFc0nx** [comment]
fixed
